### ISSUE TITLE
Line 538 XML Syntax error.

### ISSUE THREAD

**Issue by atluriharsha** [quandl/quandl-google-spreadsheet-add-on#3]
Getting a error while adding the script and saving on gDocs.

Any help is appreciated.

<a href='http://postimg.org/image/g9z5qlgn5/' target='_blank'><img src='http://s16.postimg.org/g9z5qlgn5/quandl_importer.jpg' border='0' alt="quandl importer" /></a>

**Comment by jbyck** [comment]
Hi @asharshavardhan - can you tell us how to reproduce the error?

**Comment by jbyck** [comment]
We were unable to reproduce - please feel free to re-open if you have more information.
